# Generated by Django 4.2.7 on 2025-10-14 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_consulta', models.DateTimeField(verbose_name='Fecha y hora de consulta')),
                ('motivo', models.TextField(verbose_name='Motivo de la consulta')),
                ('diagnostico', models.TextField(blank=True, verbose_name='Diagnóstico médico')),
                ('estado', models.CharField(choices=[('PROG', 'Programada'), ('CURS', 'En Curso'), ('COMP', 'Completada'), ('CANC', 'Cancelada')], default='PROG', max_length=4, verbose_name='Estado de la consulta')),
            ],
            options={
                'verbose_name': 'Consulta Médica',
                'verbose_name_plural': 'Consultas Médicas',
            },
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la especialidad')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción detallada')),
            ],
            options={
                'verbose_name': 'Especialidad',
                'verbose_name_plural': 'Especialidades',
            },
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre comercial')),
                ('laboratorio', models.CharField(max_length=100, verbose_name='Laboratorio fabricante')),
                ('stock', models.IntegerField(default=0, verbose_name='Cantidad en stock')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prixio unitario')),
                ('activo', models.BooleanField(default=True, verbose_name='Medicamento activo')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True, verbose_name='RUT del paciente')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('tipo_sangre', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, verbose_name='Tipo de sangre')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono de contacto')),
                ('direccion', models.TextField(verbose_name='Dirección particular')),
                ('activo', models.BooleanField(default=True, verbose_name='Paciente activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
            ],
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(verbose_name='Descripción del tratamiento')),
                ('duracion_dias', models.IntegerField(verbose_name='Duración en días')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones adicionales')),
                ('fecha_inicio', models.DateField(auto_now_add=True, verbose_name='Fecha de inicio del tratamiento')),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.consultamedica', verbose_name='Consulta relacionada')),
            ],
        ),
        migrations.CreateModel(
            name='RecetaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosis', models.CharField(max_length=50, verbose_name='Dosis prescrita')),
                ('frecuencia', models.CharField(max_length=100, verbose_name='Frecuencia de administración')),
                ('duracion', models.CharField(max_length=50, verbose_name='Duración del tratamiento')),
                ('fecha_prescripcion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de prescripción')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medicamento', verbose_name='Medicamento recetado')),
                ('tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tratamiento', verbose_name='Tratamiento asociado')),
            ],
            options={
                'verbose_name': 'Receta Médica',
                'verbose_name_plural': 'Recetas Médicas',
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('rut', models.CharField(max_length=12, unique=True, verbose_name='RUT del médico')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono de contacto')),
                ('activo', models.BooleanField(default=True, verbose_name='Médico activo')),
                ('fecha_contratacion', models.DateField(auto_now_add=True, verbose_name='Fecha de contratación')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.especialidad', verbose_name='Especialidad médica')),
            ],
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medico', verbose_name='Médico tratante'),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paciente', verbose_name='Paciente atendido'),
        ),
    ]
