# Generated by Django 4.2.7 on 2025-10-14 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario'),
        ),
        migrations.CreateModel(
            name='HistorialMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_evento', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del evento')),
                ('tipo_evento', models.CharField(max_length=50, verbose_name='Tipo de evento')),
                ('descripcion', models.TextField(verbose_name='Descripción detallada')),
                ('gravedad', models.CharField(choices=[('LEVE', 'Leve'), ('MODERADO', 'Moderado'), ('GRAVE', 'Grave'), ('CRITICO', 'Crítico')], default='LEVE', max_length=20, verbose_name='Nivel de gravedad')),
                ('archivos_adjuntos', models.FileField(blank=True, null=True, upload_to='historial_medico/', verbose_name='Archivos adjuntos')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones adicionales')),
                ('medico_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.medico', verbose_name='Médico responsable')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Historial Médico',
                'verbose_name_plural': 'Historiales Médicos',
                'ordering': ['-fecha_evento'],
            },
        ),
    ]
