# Generated by Django 4.2.7 on 2025-10-15 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_medicamento_precio_unitario_historialmedico'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultamedica',
            options={'ordering': ['-fecha_consulta'], 'verbose_name': 'Consulta Médica', 'verbose_name_plural': 'Consultas Médicas'},
        ),
        migrations.AlterModelOptions(
            name='medicamento',
            options={'ordering': ['nombre'], 'verbose_name': 'Medicamento', 'verbose_name_plural': 'Medicamentos'},
        ),
        migrations.AlterModelOptions(
            name='medico',
            options={'ordering': ['apellido', 'nombre'], 'verbose_name': 'Médico', 'verbose_name_plural': 'Médicos'},
        ),
        migrations.AlterModelOptions(
            name='paciente',
            options={'ordering': ['apellido', 'nombre'], 'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.AlterField(
            model_name='historialmedico',
            name='tipo_evento',
            field=models.CharField(choices=[('CONSULTA', 'Consulta'), ('EXAMEN', 'Examen'), ('PROCEDIMIENTO', 'Procedimiento'), ('ALERGIA', 'Alergia'), ('ENFERMEDAD', 'Enfermedad'), ('TRATAMIENTO', 'Tratamiento'), ('OTRO', 'Otro')], max_length=50, verbose_name='Tipo de evento'),
        ),
        migrations.AlterUniqueTogether(
            name='recetamedica',
            unique_together={('tratamiento', 'medicamento')},
        ),
    ]
